<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Анализатор страниц</title>
        <link rel="stylesheet"
              href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
              integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
              crossorigin="anonymous">
    </head>
    <body class="d-flex flex-column min-vh-100">
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Главная</a>
            </div>
        </nav>
        <main class="flex-grow-1">
            <section>
                <div class="container-fluid bg-dark p-5">
                    <div class="row">
                        <div class="col-md-10 col-lg-8 mx-auto text-white">
                            <h1 class="display-3 mb-0">Анализатор страниц</h1>
                            <p class="lead">Бесплатно проверяйте сайты на SEO пригодность</p>
                            <p class="mt-2 mb-0 text-muted">Пример: https://www.example.com</p>
                        </div>
                    </div>
                </div>
            </section>
        </main>
        <footer class="footer border-top py-3 mt-5 bg-light">
            <div class="container-xl">
                <div class="text-center">
                    created by <a href="https://ru.hexlet.io/">Hexlet</a>
                </div>
            </div>
        </footer>
    </body>
</html>